from __future__ import annotations

import io
import zipfile


def _predict_script(model_name: str, feature_names: list[str], problem_type: str) -> str:
    features_repr = repr(feature_names)
    proba_line = (
        "    probabilities = model.predict_proba(df_input)\n"
        "    return {\"predictions\": predictions.tolist(), \"probabilities\": probabilities.tolist()}\n"
        if problem_type == "classification"
        else "    return {\"predictions\": predictions.tolist()}\n"
    )
    return f'''"""
Inference script generated by AutoML Agent.
Model: {model_name}  |  Task: {problem_type}

Usage:
    python predict.py
"""
import joblib
import pandas as pd

FEATURE_NAMES = {features_repr}
MODEL_PATH = "best_model.pkl"

model = joblib.load(MODEL_PATH)


def predict(data: dict | list[dict]) -> dict:
    """
    Run inference on one or more records.

    Args:
        data: a dict of {{feature: value}} or a list of such dicts.

    Returns:
        dict with "predictions" key (and "probabilities" for classification).
    """
    records = data if isinstance(data, list) else [data]
    df_input = pd.DataFrame(records)[FEATURE_NAMES]
    predictions = model.predict(df_input)
{proba_line}

if __name__ == "__main__":
    # ── example usage ────────────────────────────────────────────────────────
    sample = {{feat: 0 for feat in FEATURE_NAMES}}
    result = predict(sample)
    print("Prediction:", result)
'''


def _serve_script(model_name: str, feature_names: list[str], problem_type: str) -> str:
    features_repr = repr(feature_names)
    return f'''"""
FastAPI inference server generated by AutoML Agent.
Model: {model_name}  |  Task: {problem_type}

Install:  pip install fastapi uvicorn joblib pandas
Run:      uvicorn serve:app --reload --port 8000
Docs:     http://localhost:8000/docs
"""
from fastapi import FastAPI
from pydantic import BaseModel
import joblib
import pandas as pd

FEATURE_NAMES = {features_repr}

app = FastAPI(title="AutoML Agent — {model_name}")
model = joblib.load("best_model.pkl")


class PredictRequest(BaseModel):
    data: list[dict]


class PredictResponse(BaseModel):
    predictions: list
    probabilities: list | None = None


@app.post("/predict", response_model=PredictResponse)
def predict(req: PredictRequest):
    df = pd.DataFrame(req.data)[FEATURE_NAMES]
    preds = model.predict(df).tolist()
    proba = None
    if hasattr(model, "predict_proba"):
        proba = model.predict_proba(df).tolist()
    return PredictResponse(predictions=preds, probabilities=proba)


@app.get("/health")
def health():
    return {{"status": "ok", "model": "{model_name}"}}
'''


def build_zip(
    model_bytes: bytes,
    model_name: str,
    feature_names: list[str],
    problem_type: str,
) -> bytes:
    """Bundle model + inference scripts into a downloadable zip."""
    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED) as zf:
        zf.writestr("best_model.pkl", model_bytes)
        zf.writestr("predict.py", _predict_script(model_name, feature_names, problem_type))
        zf.writestr("serve.py", _serve_script(model_name, feature_names, problem_type))
        zf.writestr(
            "README.md",
            f"# AutoML Agent — {model_name}\n\n"
            "## Quick start\n\n"
            "```bash\n"
            "pip install scikit-learn xgboost lightgbm joblib pandas fastapi uvicorn\n\n"
            "# Run a prediction\n"
            "python predict.py\n\n"
            "# Start the API server\n"
            "uvicorn serve:app --reload --port 8000\n"
            "```\n\n"
            f"**Task:** {problem_type}  \n"
            f"**Features:** {', '.join(feature_names)}\n",
        )
    buf.seek(0)
    return buf.read()
